name: Build and release binary of ecc (aarch64)

on:
  push:
    branches: "master"
env:
  GITHUB_REPO_OWNER: ${{ github.repository_owner }}
jobs:
  # define job to build and publish docker image
  build-and-release:
    runs-on: ubuntu-latest
    # run only when code is compiling and tests are passing
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies for cross building
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          ls /usr/lib/gcc-cross/aarch64-linux-gnu/
          aarch64-linux-gnu-gcc --version
      - name: Prepare bpftool and vmlinux repo for building workspace
        # Move more steps outside of the virtual machine
        run: |
          mkdir workspace
          mkdir assets
          cd assets
          git clone --recursive https://github.com/eunomia-bpf/vmlinux
          cd vmlinux
          git checkout 933f83b
          # Avoid symlink issues
          rm vmlinux.h
          cd ..
          git clone --recursive https://github.com/eunomia-bpf/bpftool
          cd bpftool
          git checkout 0594034
      - name: Build workspace in aarch64 virtual machine
        uses: uraimo/run-on-arch-action@v2
        with: 
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt-get update
            apt-get install -y zlib1g-dev libelf-dev gcc make
            cd /workspace && mkdir bin
            cd /assets/bpftool/src
            CFLAGS="-static" make
            cp bpftool /workspace/bin
          dockerRunArgs: |
            --volume "${PWD}/workspace:/workspace"
            --volume "${PWD}/assets:/assets"
      - name: Compose the ecc workspace
        run: |
          sudo chmod 777 workspace -R
          sudo chown `whoami` workspace -R
          cd workspace
          mkdir include
          cp -r ../assets/bpftool/src/libbpf/include/bpf include/
          cp -r ../assets/vmlinux/ include/
          cp ./include/vmlinux/arm64/vmlinux.h ./include/vmlinux
      - name: Cross build ecc (aarch64)
        run: |
          rustup target add aarch64-unknown-linux-gnu
          export ECC_CUSTOM_WORKSPACE_ROOT=$(pwd)/workspace
          echo "Workspace dir: $ECC_CUSTOM_WORKSPACE_ROOT"
          cd compiler/cmd
          cargo build --release --target aarch64-unknown-linux-gnu
          cd ../..
          mkdir data
          cp ./compiler/cmd/target/aarch64-unknown-linux-gnu/release/ecc-rs data/ecc
          ls -lah data
      # Necessary if we want to run things cross platform
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Test ecc
        uses: uraimo/run-on-arch-action@v2
        with: 
          arch: aarch64
          distro: ubuntu22.04
          run: |
            ldd /data/ecc
      - name: Run ecc-rs and retrive what libraries it loaded
        uses: uraimo/run-on-arch-action@v2
        with: 
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt-get update
            apt-get install -y libclang1
            echo "Installation done"
            echo "Working directory $(pwd)"
            chmod +x /data/ecc
            echo "Permission set done"
            LD_DEBUG=libs /data/ecc 2> ld_debug_output
            echo "ecc running done"
            library_paths=$(awk '/^.+calling init:/{print $4}' ld_debug_output)
            echo "raw library paths: $library_paths"
            for library_path in $library_paths; do
                target_path="/data/libs${library_path}"
                target_dir=$(dirname "$target_path")
                mkdir -p "$target_dir"
                echo "Copy $library_path"
                cp "$library_path" "$target_path"
            done
          dockerRunArgs: |
            --volume "${PWD}/data:/data"
          shell: /bin/bash
      - name: Show what libraries were copied
        run: |
          sudo chmod 777 ./data -R
          sudo chown $(whoami) ./data -R
          find -type f ./data/libs
